oauthexternal_list:
    pattern:  /service/list
    defaults: { _controller: EpidouxOAuthExternalBundle:Connect:list }


oauthexternal_connect:
    pattern: /service/connect/{connector}
    defaults: { _controller: EpidouxOAuthExternalBundle:Connect:connect }
