parameters:
     connector.class: Epidoux\OAuthExternalBundle\Services\ConnectorService
     oauth.class: Epidoux\OAuthExternalBundle\Services\OAuthService
     oauth.provider_factory.class: Epidoux\OAuthExternalBundle\Factories\ProviderFactory

services:
     connector.service:
        class: %connector.class%
        arguments: [%oauth.services%,%oauth.callback%,%oauth.debug%,@logger,@oauth.factory.provider]

     oauth.service:
        class: %oauth.class%
        arguments: [@logger]

     oauth.factory.provider:
        class: %oauth.provider_factory.class%
        arguments: []